### ISSUE TITLE
Message overrides do not update the UI

### ISSUE THREAD

**Issue by daniel-lerch** [skynet-im/skynet-android#24]
**To Reproduce**
1. Open a chat in Skynet
2. Tell your friend to send you a message
3. Tell your friend to edit or delete this message
4. You will not see the change of your friend
5. Leave the chat and open it again
6. You will see the change of your friend

**Expected behavior**
Skynet should automatically update the UI to show any changes immediately.

**Smartphone (please complete the following information):**
 - Device: Galaxy S6, AOSP on IA Emulator (AVD)
 - OS: Android 7, Android 9

**Additional context**
Even sending or receiving a new message does not reveal your friend's change.

**Comment by Twometer** [comment]
Apparently, it tries to update the message id of the override, not the referenced message. This is a very unfortunate bug that happened during the protocol update.
The old protocol had a field in the packet called "messageId", which represented the referenced message. With the update, this field got removed and instead every channel message now inherits the channelmessagepacket which again, has a field "messageId". With a different meaning. Therefore this bug was never found with the compiler erros
