### ISSUE TITLE
Message formatting

### ISSUE THREAD

**Issue by daniel-lerch** [skynet-im/skynet-android#26]
There are few things related to message formatting that should be improved:
1. Large size emojis
_Special rendering for messages that only consist of emojis._
2. Message trimming
_Cut off white space chars at both ends of a message and find a reasonable line limit to prevent people from writing messages that take too long to scroll._
3. Markdown support
_Bold, italics and monospace. Other features will be added later._
4. Link detection
_The client should detect URLs in messages and display clickable links. For developers it would be very nice if messages like ASP.NET or Rocket.Chat would not be detected as links because they don't have a URI scheme and are written in uppercase._
5. Optimized rendering for multi line messages
_Long message have too much padding on the right side which wastes a lot of space on mobile devices._

**Comment by Twometer** [comment]
Regarding suggestion No 2: We should make it like whatsapp so that it shows a "Read more" button after X characters, but I would not prevent people from writing long messages.

**Comment by daniel-lerch** [comment]
A _read more_ button sounds good.

Channel messages technically support texts lengths of at least 50&nbsp;KB. If I send you message with one line text, 50,000 new lines and another line text you will be busy for minutes to scroll to the end and we might encounter rendering issues. That was the reason for me to limit the number of lines and not only the text length in bytes.

**Comment by daniel-lerch** [comment]
A screenshot for point 5:

![Screenshot_20200419-140404](https://user-images.githubusercontent.com/36048059/79687308-b2f5db80-8246-11ea-8863-29a04fef227c.png)

**Comment by Twometer** [comment]
For point 5, that's a bit of a complicated problem, because we would have to overlay the metadata views (time, state, edited...) on the right on top of the text field, **but only if it has space there**. We don't want the overlap for single line messages. I'll look into that if there is an easy way to detect this.

For point 4, we can do that but then things like google.com would not be recognized. Even if we filter for TLDs, ASP.NET will be recognized since it's a valid domain and redirects to `https://dotnet.microsoft.com/apps/aspnet`. We could check for uppercase TLDs and discard those, but this again would mean if you send a quick message like `I'm gonna implement this using an asp.net service tomorrow`, it will again be detected.
What do you think?

**Comment by daniel-lerch** [comment]
For point 5, I would simply render the meta data below the message text if the message has more than 2 lines. In this case we would have more padding at the bottom but it would look better. Maybe that's not too complicated to implement.

For point 4, let's exclude only uppercase TLDs because most names are officially written with at least one upper case letter. As long as it is just a clickable link and not a huge link preview, it won't be too annoying for me.
If we implement link previews in the future we can implement further exclusions or settings for those but that's not necessary now.
